/**
 * github.js — GitHub API service via Octokit
 *
 * Handles reading translation files from repos and committing updated
 * translations back via branches + pull requests.
 */

import { Octokit } from '@octokit/rest';
import dotenv from 'dotenv';

dotenv.config();

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

/**
 * Parse "owner/repo" string.
 */
function splitRepo(fullRepo) {
  const [owner, repo] = fullRepo.split('/');
  return { owner, repo };
}

// ── Read ─────────────────────────────────────────────────────────────

/**
 * Fetch the raw content + SHA of a file from a GitHub repo.
 * Returns { content: string, sha: string }
 */
export async function getFileContent(fullRepo, path, branch = 'main') {
  const { owner, repo } = splitRepo(fullRepo);

  const { data } = await octokit.repos.getContent({
    owner,
    repo,
    path,
    ref: branch,
  });

  if (Array.isArray(data)) {
    throw new Error(`"${path}" is a directory, expected a file`);
  }

  const content = Buffer.from(data.content, 'base64').toString('utf-8');
  return { content, sha: data.sha };
}

// ── Write (Branch → Commit → PR) ────────────────────────────────────

/**
 * Get the SHA of a branch's HEAD.
 */
async function getBranchSha(fullRepo, branch) {
  const { owner, repo } = splitRepo(fullRepo);
  const { data } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${branch}`,
  });
  return data.object.sha;
}

/**
 * Create a new branch from an existing branch.
 */
async function createBranch(fullRepo, baseBranch, newBranch) {
  const { owner, repo } = splitRepo(fullRepo);
  const sha = await getBranchSha(fullRepo, baseBranch);

  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${newBranch}`,
    sha,
  });

  return sha;
}

/**
 * Update (or create) a file on a given branch.
 */
async function updateFile(fullRepo, branch, path, content, message, sha) {
  const { owner, repo } = splitRepo(fullRepo);

  const { data } = await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path,
    message,
    content: Buffer.from(content, 'utf-8').toString('base64'),
    sha,
    branch,
  });

  return data;
}

/**
 * Open a pull request.
 */
async function openPullRequest(fullRepo, head, base, title, body) {
  const { owner, repo } = splitRepo(fullRepo);

  const { data } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body,
    head,
    base,
  });

  return data;
}

// ── Orchestrator ─────────────────────────────────────────────────────

/**
 * Commit updated translations and open a PR.
 *
 * Flow:
 *   1. Create branch `translations/batch-{timestamp}`
 *   2. Commit the updated translation file
 *   3. Open a PR back to the base branch
 *
 * @returns {{ prUrl: string, branchName: string }}
 */
export async function commitTranslations({
  fullRepo,
  baseBranch,
  filePath,
  fileContent,
  fileSha,
  changedKeys,
}) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const branchName = `translations/batch-${timestamp}`;

  // 1. Create branch
  await createBranch(fullRepo, baseBranch, branchName);

  // 2. Commit updated file
  const commitMessage = `chore(i18n): update ${changedKeys.length} Japanese translation(s)\n\nKeys updated:\n${changedKeys.map(k => `  - ${k}`).join('\n')}\n\nGenerated by Translation Moderator`;

  await updateFile(fullRepo, branchName, filePath, fileContent, commitMessage, fileSha);

  // 3. Open PR
  const prTitle = `🌏 Translation update — ${changedKeys.length} key(s) reviewed`;
  const prBody = [
    '## Translation Moderator — Human Review',
    '',
    `**${changedKeys.length}** Japanese translation(s) were reviewed and updated by a human translator.`,
    '',
    '### Changed Keys',
    '',
    '| Key | Status |',
    '|-----|--------|',
    ...changedKeys.map(k => `| \`${k}\` | ✅ Reviewed |`),
    '',
    '---',
    '_This PR was auto-generated by the Translation Moderator._',
  ].join('\n');

  const pr = await openPullRequest(fullRepo, branchName, baseBranch, prTitle, prBody);

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    branchName,
  };
}

/**
 * List open translation PRs for a repo.
 */
export async function getOpenTranslationPRs(fullRepo) {
  const { owner, repo } = splitRepo(fullRepo);

  const { data } = await octokit.pulls.list({
    owner,
    repo,
    state: 'open',
    head: `${owner}:translations/`,
    per_page: 10,
  });

  // Filter to only translation branches
  return data
    .filter(pr => pr.head.ref.startsWith('translations/'))
    .map(pr => ({
      number: pr.number,
      title: pr.title,
      url: pr.html_url,
      createdAt: pr.created_at,
      branch: pr.head.ref,
    }));
}
